Add mock assert rule
mytestopia/flake8-vedro pull request #5
Opened 2024-12-06 13:41 UTC by FiruzShoev

Asserting mocks can be helpful to check mock history

2024-12-09 11:06 UTC, azolotyk commented on README.md
> +14. [VDR313. Mock call result should be saved as "self" attribute for assert in further steps](./flake8_vedro/rules/VDR313.md)
[Optional]

```suggestion
14. [VDR313. Mock call result should be saved as "self" attribute for further assertion](./flake8_vedro/rules/VDR313.md)
```

2024-12-09 11:06 UTC, azolotyk commented on flake8_vedro/errors/errors.py
> +    message = 'Result of "{mock_func_name}()" should be saved as "self" attribute for assert in further steps'
[Optional]

```suggestion
    message = 'Result of "{mock_func_name}()" should be saved as "self" attribute for further assertion'
```

2024-12-09 11:06 UTC, azolotyk commented on flake8_vedro/errors/errors.py
> +    message = 'Result of "{mock_func_name}()" should be saved as "self" attribute for assert in further steps'
Во всех остальных сообщениях об ошибках текст начинается с маленькой буквы. Давай и тут поправим?

2024-12-09 11:06 UTC, azolotyk commented on README.md
> +14. [VDR313. Mock call result should be saved as "self" attribute for assert in further steps](./flake8_vedro/rules/VDR313.md)
Ну и ниже в самих правилах тоже.

2024-12-09 11:06 UTC, azolotyk commented on flake8_vedro/abstract_checkers/scenario_helper.py
> +    def get_then_and_but_steps(self, steps: List) -> List:
Похихикала тут от того, что метод должен называться `get_then_and_and_and_but_steps`

2024-12-12 06:55 UTC, mytestopia requested changes

2024-12-12 06:55 UTC, mytestopia commented on flake8_vedro/rules/VDR313.md
> +### ✅Best practice
пробельчик давай добавим после галочки :)

2024-12-12 06:55 UTC, mytestopia commented on flake8_vedro/visitors/steps_checkers/mock_assert_checker.py
> +        then_and_but_steps = self.get_then_and_but_steps(context.steps)
можно проще - assertion_steps

2024-12-12 06:55 UTC, mytestopia commented on flake8_vedro/visitors/steps_checkers/mock_assert_checker.py
> +def _is_self_attribute(node: ast.expr) -> bool:
может потребоваться не только для этого правила, предлагаю вынести в helpers

2024-12-12 06:55 UTC, mytestopia commented on flake8_vedro/visitors/steps_checkers/mock_assert_checker.py
> +    return False
я бы разнесла на разные методы:
- генератор на получение всех ассертов в проверочных шагах (можно будет переиспользовать и тоже вынести в хелпер)
- проход по генератору и проверка условия

2024-12-12 06:55 UTC, mytestopia commented on tests/test_mock_assert.py
> +                with mocked_hotel(): pass
не вижу тестов на кейсы
```python
async with mocked(): pass

with mocked_1():
  with mocked_2():
     pass

with (
  mocked_1(),
  mocked_2()
): 
  pass
```
Для них правило с self работает?

2024-12-12 06:55 UTC, mytestopia commented on flake8_vedro/visitors/steps_checkers/mock_assert_checker.py
> +                    mock_context_managers.append((item, statement.lineno, statement.col_offset))
Помимо http моков в тестах могут быть еще mq и grpc моки, которые с точки зрения интерфейса выглядят так же, но для grpc история отсутствует вообще, соответственно на них это правило не распространить. И если такие моки в проекте существуют, то правило VDR313  включить будет нельзя вообще для всех моков

Пример grpc
```python
async def when_user_gets_branch_reviews_sorted_by_friends(self):
    with mocked_auth_user(self.user) as self.user_history:  # http mock
        with mocked_token_info(self.user) as self.token_history:   # http mock
            async with mocked_social_graph_response(self.user, self.visible_profiles):   # grpc mock
                self.response = ReviewsApi(self.user).get_branch_reviews(...)
```
Пример mq (с историей)
```python
async def when_worker_starts(self):
    async with mocked_queue(ContestQueue, self.message) as self.queue_history:  # mq mock
        with participant_mocked_response([self.user]) as self.history:  # http mock
            self.stdout, self.stderr = PhotoCli().process_contest_queue(...)
```
Плюс, не все моки всегда именуются одинаково (а правило завязано на то, что мок - это контекстный менеджер, название которого начинается с "mock".

Тогда, например, можно сделать еще один параметр, в котором будет передаваться регулярка того, как называются моки, которую можно будет конфигурировать под проект. По дефолту - твое правило, в частности, например, регулярка, которая будет содержать mocked и исключать grpc

2024-12-17 15:31 UTC, FiruzShoev commented on tests/test_mock_assert.py
> +                with mocked_hotel(): pass
Добавил

2024-12-17 15:35 UTC, FiruzShoev commented on README.md
> +14. [VDR313. Mock call result should be saved as "self" attribute for assert in further steps](./flake8_vedro/rules/VDR313.md)
Поправил

2024-12-17 15:35 UTC, FiruzShoev commented on flake8_vedro/errors/errors.py
> +    message = 'Result of "{mock_func_name}()" should be saved as "self" attribute for assert in further steps'
Поправил

2024-12-17 15:36 UTC, FiruzShoev commented on flake8_vedro/abstract_checkers/scenario_helper.py
> +    def get_then_and_but_steps(self, steps: List) -> List:
Теперь get_assertion_steps 😄

2024-12-17 15:36 UTC, FiruzShoev commented on flake8_vedro/rules/VDR313.md
> +### ✅Best practice
Поправил

2024-12-17 15:36 UTC, FiruzShoev commented on flake8_vedro/visitors/steps_checkers/mock_assert_checker.py
> +        then_and_but_steps = self.get_then_and_but_steps(context.steps)
Поправил

2024-12-17 15:36 UTC, FiruzShoev commented on flake8_vedro/visitors/steps_checkers/mock_assert_checker.py
> +def _is_self_attribute(node: ast.expr) -> bool:
Вынес

2024-12-17 15:36 UTC, FiruzShoev commented on flake8_vedro/visitors/steps_checkers/mock_assert_checker.py
> +    return False
Разнёс)

2024-12-17 18:00 UTC, FiruzShoev commented on flake8_vedro/visitors/steps_checkers/mock_assert_checker.py
> +                    mock_context_managers.append((item, statement.lineno, statement.col_offset))
Добавил параметр `mock_name_pattern`

2024-12-26 13:40 UTC, closed without merging